# ci/github-actions/all-modules.cmake

set(VRN_OPENGL_COMPATIBILITY_PROFILE OFF CACHE BOOL "" FORCE) #required to build some modules, see below
set(VRN_BUILD_VOREENVE ON CACHE BOOL "" FORCE)
set(VRN_BUILD_VOREENTOOL ON CACHE BOOL "" FORCE)
set(VRN_BUILD_SIMPLEGLUT ON CACHE BOOL "" FORCE)
set(VRN_BUILD_SIMPLEQT ON CACHE BOOL "" FORCE)
set(VRN_BUILD_TESTAPPS ON CACHE BOOL "" FORCE)
set(VRN_BUILD_BLASTEST ON CACHE BOOL "" FORCE)
set(VRN_BUILD_ITKWRAPPER OFF CACHE BOOL "" FORCE) # deprecated
set(VRN_DEPLOYMENT OFF CACHE BOOL "" FORCE) # no deployment build
set(VRN_NON_INTERACTIVE ON CACHE BOOL "" FORCE) # fall through assertion while testing

# Modules
set(VRN_MODULE_BASE ON CACHE BOOL "" FORCE)
set(VRN_MODULE_BIGDATAIMAGEPROCESSING ON CACHE BOOL "" FORCE)
set(VRN_MODULE_CONNEXE ON CACHE BOOL "" FORCE)
set(VRN_MODULE_DEPRECATED OFF CACHE BOOL "" FORCE) # compatibility
set(VRN_MODULE_DEVIL ON CACHE BOOL "" FORCE)
set(VRN_MODULE_DYNAMICGLSL OFF CACHE BOOL "" FORCE) # compatibility
set(VRN_MODULE_ENSEMBLEANALYSIS ON CACHE BOOL "" FORCE)
set(VRN_MODULE_EXPERIMENTAL OFF CACHE BOOL "" FORCE) # compatibility
set(VRN_MODULE_FFMPEG OFF CACHE BOOL "" FORCE)
set(VRN_MODULE_FLOWANALYSIS ON CACHE BOOL "" FORCE)
set(VRN_MODULE_FLOWSIMULATION ON CACHE BOOL "" FORCE)
set(VRN_MODULE_GDCM ON CACHE BOOL "" FORCE)
set(VRN_MODULE_HDF5 ON CACHE BOOL "" FORCE)
set(VRN_USE_HDF5_VERSION 1.10 CACHE STRING "" FORCE)
set(VRN_MODULE_ITK OFF CACHE BOOL "" FORCE) # deprecated
set(VRN_MODULE_OPENCL OFF CACHE BOOL "" FORCE) # requires additional setup
set(VRN_MODULE_OPENMP ON CACHE BOOL "" FORCE)
set(VRN_MODULE_PLOTTING ON CACHE BOOL "" FORCE)
set(VRN_MODULE_POI ON CACHE BOOL "" FORCE)
set(VRN_MODULE_PVM ON CACHE BOOL "" FORCE)
set(VRN_MODULE_PYTHON ON CACHE BOOL "" FORCE)
set(VRN_MODULE_RANDOMWALKER ON CACHE BOOL "" FORCE)
set(VRN_MODULE_SEGY ON CACHE BOOL "" FORCE)
set(VRN_MODULE_STAGING ON CACHE BOOL "" FORCE)
set(VRN_MODULE_STEREOSCOPY ON CACHE BOOL "" FORCE)
set(VRN_MODULE_SURFACE ON CACHE BOOL "" FORCE)
set(VRN_MODULE_TIFF ON CACHE BOOL "" FORCE)
set(VRN_MODULE_TOUCHTABLE OFF CACHE BOOL "" FORCE) # deprecated
set(VRN_MODULE_VESSELNETWORKANALYSIS ON CACHE BOOL "" FORCE)
set(VRN_MODULE_VOLUMELABELING OFF CACHE BOOL "" FORCE) # compatibility
set(VRN_MODULE_VTK ON CACHE BOOL "" FORCE)
set(VRN_MODULE_ZIP ON CACHE BOOL "" FORCE)
